[editor]
line-number = "relative"

[editor.indent-guides]
render = true
character = "|"
#skip-levels = 1

[editor.whitespace]
render = "all"
# or control each character

[editor.whitespace.characters]
space = "·"
nbsp = "⍽"
tab = "→"
newline = "⏎"
tabpad = "·" # Tabs will look like "→···" (depending on tab width)